import { proxyActivities, defineSignal, setHandler, condition } from '@temporalio/workflow';
import type * as activities from './activities';

const {
  generateCurriculum,
  generateLessonsAndEmbeddings,
  startVideoRendering,
  setCourseStatus,
  updateCourseProgress,
  compensateCurriculum,
  compensateEmbeddings,
  compensateVideo,
} = proxyActivities<typeof activities>({
  startToCloseTimeout: '30 minutes',
  retry: {
    initialInterval: '2s',
    backoffCoefficient: 2,
    maximumInterval: '30s',
    maximumAttempts: 3,
  },
});

// Signals
export const HeyGenWebhookSignal = defineSignal<[{ videoUrl: string; success: boolean }]>('HeyGenWebhookSignal');

interface WorkflowInput {
  courseId: string;
  userId: string;
  tenantId: string;
  topic: string;
  duration?: string;
}

export async function CourseGenerationWorkflow(input: WorkflowInput): Promise<string> {
  const { courseId, tenantId, topic, duration } = input;
  
  // Saga compensation stack
  const compensations: Array<() => Promise<void>> = [];
  let videoUrlResult = '';
  let signalReceived = false;

  // Register signal handler
  setHandler(HeyGenWebhookSignal, (payload) => {
    if (payload.success) {
      videoUrlResult = payload.videoUrl;
    }
    signalReceived = true;
  });

  try {
    // Initial Progress
    await updateCourseProgress(courseId, 5, 'Starte Kursgenerierung...');

    // Steps 1 & 2 (Curriculum & Lessons Content) are pre-generated by the admin in the wizard interface.
    // We start directly with Step 3: Media rendering.

    // 3. Initiate ElevenLabs Audio and HeyGen Avatar Video rendering (Saga Step 3)
    await updateCourseProgress(courseId, 80, 'Rendere Video-Avatare und Sprache...');
    const { videoId, awaitWebhook, mediaUrl } = await startVideoRendering(courseId, tenantId);
    compensations.push(async () => {
      if (videoId) {
        console.log(`[SAGA COMPENSATION] Cancelling video render job ${videoId}`);
        await compensateVideo(videoId);
      }
    });

    if (awaitWebhook) {
      // 4. Wait for external webhook signal (Await pattern)
      // We wait up to 5 minutes (300,000 milliseconds) for rendering to finish.
      await updateCourseProgress(courseId, 90, 'Warte auf Avatar-Rendering (Webhook)...');
      const hasSignal = await condition(() => signalReceived, '5 minutes');
      
      if (!hasSignal) {
        throw new Error('Timeout: Video rendering did not complete within 5 minutes.');
      }

      if (!videoUrlResult) {
        throw new Error('Video rendering failed or rejected.');
      }

      // 5. Success: Transition course to pending_approval (Admin must approve)
      await updateCourseProgress(courseId, 95, 'Schließe Generierung ab...');
      await setCourseStatus(courseId, 'pending_approval', videoUrlResult);
    } else {
      // 5. Success: Transition course to pending_approval.
      // Per-lesson audio URLs were already saved in startVideoRendering — do not pass mediaUrl
      // here (that would overwrite every lesson with the first lesson's audio).
      await updateCourseProgress(courseId, 95, 'Schließe Generierung ab...');
      await setCourseStatus(courseId, 'pending_approval');
    }
    
    // Complete progress
    await updateCourseProgress(courseId, 100, 'Bereit zur Freigabe');
    
    return `Course ${courseId} successfully generated and pending approval.`;
  } catch (error: any) {
    console.error(`Workflow failed: ${error.message}. Running compensating actions in reverse order...`);
    
    // Execute compensations in LIFO (last-in, first-out) order
    for (let i = compensations.length - 1; i >= 0; i--) {
      try {
        await compensations[i]();
      } catch (compErr: any) {
        console.error(`Compensating action failed: ${compErr.message}`);
      }
    }

    // Set course status to failed
    await setCourseStatus(courseId, 'failed');
    
    throw error;
  }
}
