import { db } from './index';
import { sql } from 'drizzle-orm';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import * as path from 'path';

export async function runMigrations() {
  console.log('Running Drizzle migrations...');
  
  // 1. Enable pgvector and pg_trgm extensions first so vector types are available
  await db.execute(sql`CREATE EXTENSION IF NOT EXISTS vector;`);
  await db.execute(sql`CREATE EXTENSION IF NOT EXISTS pg_trgm;`);

  // 2. Run migrations generated by drizzle-kit
  await migrate(db, { migrationsFolder: path.join(process.cwd(), 'drizzle') });
  
  console.log('Drizzle migrations completed.');
  console.log('Applying custom RLS and Index DDL...');

  // 3. Create HNSW index on the embeddings table
  // HNSW requires vector_cosine_ops or vector_l2_ops. We use cosine similarity (vector_cosine_ops).
  await db.execute(sql`
    CREATE INDEX IF NOT EXISTS embeddings_hnsw_idx ON embeddings 
    USING hnsw (embedding vector_cosine_ops);
  `);

  // 4. Enable Row-Level Security (RLS) on embeddings table
  await db.execute(sql`ALTER TABLE embeddings ENABLE ROW LEVEL SECURITY;`);
  await db.execute(sql`ALTER TABLE embeddings FORCE ROW LEVEL SECURITY;`);

  // 5. Create Tenant Isolation Policy
  // This policy ensures that any query to 'embeddings' is automatically filtered
  // by the session variable 'app.current_tenant_id'.
  await db.execute(sql`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'embeddings' AND policyname = 'tenant_isolation_policy'
      ) THEN
        CREATE POLICY tenant_isolation_policy ON embeddings
        FOR ALL
        USING (
          tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid
        );
      END IF;
    END
    $$;
  `);

  // 6. Create a non-superuser app role for RLS validation
  await db.execute(sql`
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'elearning_app') THEN
        CREATE ROLE elearning_app WITH LOGIN PASSWORD 'elearning_app_password';
      END IF;
    END
    $$;
  `);

  // GRANT can fail with "tuple concurrently updated" when multiple processes
  // (server + start.bat + worker) run migrations at the same time. Retry briefly.
  for (let attempt = 1; attempt <= 5; attempt++) {
    try {
      await db.execute(sql`GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO elearning_app;`);
      await db.execute(sql`GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO elearning_app;`);
      await db.execute(sql`ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO elearning_app;`);
      break;
    } catch (err: any) {
      const msg = String(err?.message || err);
      if (!msg.includes('tuple concurrently updated') || attempt === 5) {
        throw err;
      }
      console.warn(`[migrations] GRANT conflict (attempt ${attempt}/5), retrying...`);
      await new Promise((r) => setTimeout(r, 200 * attempt));
    }
  }

  console.log('Custom RLS, pgvector Index and non-superuser role applied successfully.');
}

// Allow running migrations directly from the CLI
if (require.main === module) {
  runMigrations()
    .then(() => {
      console.log('All migrations completed successfully.');
      process.exit(0);
    })
    .catch((err) => {
      console.error('Migration failed:', err);
      process.exit(1);
    });
}
